# Generated by Django 4.2.28 on 2026-02-26 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(default=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='authentication.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='authentication.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_time_start', models.TimeField()),
                ('reserved_time_end', models.TimeField()),
                ('duration', models.IntegerField(default=0, editable=False)),
                ('problem', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('ACCEPTED', 'تایید شده'), ('REJECTED', 'رد شده'), ('DONE', 'انجام شده'), ('CANCELLED', 'کنسل شده'), ('ABSENT', 'غایب')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='patient_management.patient')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='patient_management.doctorschedule')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='medical_history/')),
                ('title', models.CharField(max_length=100)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_management.patienthistory')),
            ],
        ),
    ]
